import './tasks/build/resources';
import './tasks/build/compile/scss';
import './tasks/build/compile/typescript';
import './tasks/build/bundle/bundle';
import './tasks/build/bundle/bundles-paths';
import './tasks/bump-versions';
import './tasks/change-prefix';
import './tasks/docs/docs';
import './tasks/build/build';
